### ISSUE TITLE
 Error loading script: stablecascade_diffusers.py  under A1111 v1.10.0-RC-60-g8b3d98c5a 

### ISSUE THREAD

**Issue by cibernicola** [DenOfEquity/StableCascade-for-webUI#2]
Don't know if tested under A1111 v1.10.0-RC-60-g8b3d98c5a  in Windows, but in my context I get this:
```
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "***\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "***\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "***\stable-diffusion-webui\extensions\StableCascade-for-webUI\scripts\stablecascade_diffusers.py", line 7, in <module>
        from diffusers import StableCascadeDecoderPipeline, StableCascadePriorPipeline, StableCascadeUNet#, DDPMWuerstchenScheduler
    ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (***\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)
```

**Comment by DenOfEquity** [comment]
Seems like your version of diffusers is too old, from before Stable Cascade support was added. The error shows failure to load one of the pipelines.
Check the ```requirements_versions.txt``` file in the webui directory, add /update a line for diffusers ```diffusers>=0.28.1``` (latest release is currently 0.29.2, but 0.28.1 is minimum for Cascade). Fully restart A1111 and it should update. If it doesn't, you can update manually by opening a command line in the webui directory, activating the virtual environment with ```venv\scripts\activate```, then ```pip install diffusers --upgrade```. Note that if there is a line in the requirements file specifying an earlier release, you could get downgraded when starting the server. If you're feeling cautious, you could backup your current venv first (many files, will be slow).
I've tested with A1111 v1.9.3, yesterday, and it worked for me.

**Comment by cibernicola** [comment]
Correct, working, I also had to update pytorch and cuda.
Thank you!

**Comment by DenOfEquity** [comment]
Glad to hear it.
I guess the PyTorch update was to >=2.2.0? For bfloat16 support. Not supported on my old graphics card, so I've never needed that update. I'll improve detection / messaging / fallback to float16 in an update.
